### ISSUE TITLE
noob-question about "Getting Started with Fan SHIM"

### ISSUE THREAD

**Issue by Dimpelmoser** [openoms/raspiblitz#55]
Hi openoms,

... sorry, I have a noob-question about "Getting Started with Fan SHIM".
You wrote about "Fan shim" on "rootzol / Raspiblitz" and I think that maybe you can help me.

I'm running a raspiblitz v1.2 on a 3B+ board and trying to run a "fan shim" on it.

I have followed the tutorial several times (https://learn.pimoroni.com/tutorial/sandyj/getting-started-with-fan-shim).

---------------------------

my proceeding:

- call console / terminal via putty,
- git clone https://github.com/pimoroni/fanshim-python
  cd fanshim-python
- (return)
- sudo ./install.sh
- (return)
- (reboot)
- call console / terminal via putty,
- cd examples
- (return)
- cd fanshim-python
- (return)
-  sudo ./install-service.sh 65 5
- (return)
- (reboot)

Obviously, no errors are recognizable during the installation

---------------------------

However, the "fan shim" always runs only in continuous operation and can not be controlled via the small pressure button.
The command:
cd examples
sudo ./install-service.sh 65 5
also remains after the installation without effect.

Please, what am I doing wrong?

Thanks

**Comment by Dimpelmoser** [comment]
Hi openom,
... meanwhile I get in touch with Pinoroni via their GitHub page.
Therefore I would like to be so fair to indemnify you to deal with my question.
Apart from that today my raspiblitz-blockchain has been corrumped, and it needs again "a few many days" until my raspiblitz is ready to implement the Pimoroni proposals ...

**Comment by openoms** [comment]
Hi. I can confirm that the button does not let me enter manual mode as written here:
https://learn.pimoroni.com/tutorial/sandyj/getting-started-with-fan-shim
"The LED indicates the status of the fan with green being on and red being off. A long press on the button put the fan into manual mode and then a short press will stop or start the fan. Long pressing again will re-enable automatic mode."

Other than that everything works. Can set thresholds and the LED on and off.
Worth to have look at here: 
https://github.com/pimoroni/fanshim-python/tree/master/examples

Will close this issues as the discussion is going on here: https://github.com/pimoroni/fanshim-python/issues/18
